[project]
name = "text-to-speech"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pyttsx3>=2.98",
    "streamlit>=1.44.1",
    "streamlit-extras>=0.6.0",
]
